# countries=("Pakistan","india","England","Germany")
# temp=list(countries)
# print(temp)
# print(type(temp))
# temp.append("Russia")
# print(temp)
# temp.pop(1)
# print(temp)
# countries=tuple(temp)
# print(countries)
# print(type(countries))

countries=("Pakistan","india","England","Germany","Pakistan")
# #print(countries.count("Pakistan"))
# print(countries.index("Pakistan"))

# tuple1=[1,2,3,2,3,5,4,32]
# res=tuple1.index(3,4,8)
# print(3)
print(len(countries))